from django.shortcuts import render

def home(request): return render(request, 'home.html')
def stack(request): return render(request, 'stack.html')
def queue(request): return render(request, 'queue.html')
def bfs(request): return render(request, 'bfs.html')
def dfs(request): return render(request, 'dfs.html')
def dijkstra(request): return render(request, 'dijkstra.html')
def astar(request): return render(request, 'astar.html')
def binary(request): return render(request, 'binary.html')
def sorting(request): return render(request, 'sorting.html')
def linkedlist(request): return render(request, 'linkedlist.html')
def tree(request): return render(request, 'tree.html')
def hashtable(request): return render(request, 'hashtable.html')
def kruskal(request): return render(request, 'kruskal.html')
def bellmanford(request): return render(request, 'bellmanford.html')
def login(request): return render(request, 'login.html')
def insertion(request): return render(request, 'insertion.html')
def linear(request): return render(request, 'linear.html')
